"""LCEL RAG chain: retrieve once, answer via Gemini, cite programmatically.

The chain retrieves documents exactly once and fans that same list out to
both the prompt context and the final output, so citations are always built
from the very chunks the answer was actually grounded on — never asked of
the LLM.
"""

from langchain_core.documents import Document
from langchain_core.language_models import BaseChatModel
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import Runnable, RunnableLambda, RunnableParallel, RunnablePassthrough
from langchain_google_genai import ChatGoogleGenerativeAI

from src.retrieval.retriever import Retriever
from src.utils.config import GEMINI_API_KEY, GEMINI_MODEL, GEMINI_TEMPERATURE, SYSTEM_PROMPT
from src.utils.logger import get_logger

logger = get_logger(__name__)

_PROMPT = ChatPromptTemplate.from_messages(
    [
        ("system", SYSTEM_PROMPT),
        ("human", " CONTEXT \n{context}\n\n QUESTION \n{question}"),
    ]
)


def get_llm() -> ChatGoogleGenerativeAI:
    """Construct the shared Gemini chat model from config.

    Returns:
        A ChatGoogleGenerativeAI instance, to be injected into
        create_rag_chain rather than constructed by its consumers.
    """
    logger.info("Loading Gemini model: %s", GEMINI_MODEL)
    return ChatGoogleGenerativeAI(model=GEMINI_MODEL, google_api_key=GEMINI_API_KEY, temperature=GEMINI_TEMPERATURE)


def create_rag_chain(retriever: Retriever, llm: BaseChatModel) -> Runnable:
    """Build the LCEL RAG chain.

    Input: {"question": str, "filters": dict | None}. Retrieval runs exactly
    once via a RunnableLambda; the resulting documents are fanned out to
    both the prompt context and the final output via RunnableParallel, so
    the answer and its citations are always grounded in the same chunks.

    Args:
        retriever: Injected retriever exposing .retrieve(question, filters).
        llm: Injected chat model.

    Returns:
        A Runnable that outputs {"answer": str, "documents": list[Document]}.
    """

    def _retrieve(inputs: dict) -> list[Document]:
        return retriever.retrieve(inputs["question"], inputs.get("filters"))

    def _format_context(inputs: dict) -> str:
        return _render_context(inputs["documents"])

    return (
        RunnablePassthrough.assign(documents=RunnableLambda(_retrieve))
        | RunnablePassthrough.assign(context=RunnableLambda(_format_context))
        | RunnableParallel(
            answer=_PROMPT | llm | StrOutputParser(),
            documents=RunnableLambda(lambda inputs: inputs["documents"]),
        )
    )


def ask(chain: Runnable, question: str, filters: dict | None = None) -> dict:
    """Invoke the RAG chain and build citations programmatically.

    Args:
        chain: A Runnable built by create_rag_chain.
        question: The user's question.
        filters: Optional metadata filters, passed through to retrieval.

    Returns:
        {"answer": str, "citations": list[dict], "documents": list[Document]}.
        "citations" are deduplicated (source, section, chunk_id) triples,
        derived directly from the retrieved Documents' metadata — never
        generated by the LLM. "documents" are the same raw Document objects
        the chain retrieved and grounded the answer on, in retrieval rank
        order and not deduplicated — retrieval is not re-run to produce them.
    """
    result = chain.invoke({"question": question, "filters": filters})
    return {
        "answer": result["answer"],
        "citations": _build_citations(result["documents"]),
        "documents": result["documents"],
    }


def _render_context(documents: list[Document]) -> str:
    """Render retrieved documents with explicit numbered source separators."""
    if not documents:
        return "No relevant context was retrieved."
    parts = []
    for i, doc in enumerate(documents, start=1):
        parts.append(f"SOURCE [{i}]")
        parts.append(f"metadata: {doc.metadata}")
        parts.append(f"content: {doc.page_content}")
    return "\n".join(parts)


def _build_citations(documents: list[Document]) -> list[dict]:
    """Build deduplicated (source, section, chunk_id) citations from documents, in order."""
    seen: set[tuple] = set()
    citations = []
    for doc in documents:
        metadata = doc.metadata
        triple = (metadata.get("source"), metadata.get("section"), metadata.get("chunk_id"))
        if triple in seen:
            continue
        seen.add(triple)
        citations.append({"source": triple[0], "section": triple[1], "chunk_id": triple[2]})
    return citations
